config/routes.rb
Rails.application.routes.draw do
  resources :answers
  resources :questions
  root 'home#index'
  get '/about' => 'home#about'
  post '/questions' => 'home#temp'
  get '/questions/:id' => 'home#question'
  post '/answers' => 'home#answer'
  # get 'home/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question
  include HasGravatar
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/concerns/has_gravatar.rb
module HasGravatar
  def gravatar
    "https://www.gravatar.com/avatar/#{Digest::MD5.hexdigest(email)}"
  end
end

app/models/question.rb
class Question < ApplicationRecord

  has_many :answers
  include HasGravatar
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  def create
    question = Question.find(params[:answer][:question_id])
    answer = question.answers.create(answer_params)
    MainMailer.notify_question_author(answer).deliver_later
    session[:current_user_email] = answer_params[:email]
    redirect_to question
  end

  private
  def answer_params
    params.require(:answer).permit(:email, :body)
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @questions = Question.order(created_at: :desc).all
  end

  def about
  end

  def temp
    redirect_to root_path
  end

  def answer
    redirect_to root_path
  end 
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def create 
    Question.create(question_params)
    session[:current_user_email] = question_params[:email]
    redirect_to root_path
  end

  def show
    @question = Question.find(params[:id])
    @answers = @question.answers.order(created_at: :desc).all
  end
  private
  def question_params
    params.require(:question).permit(:email, :body)
  end
  
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_user_email
    session[:current_user_email]
  end
  
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/home/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="/">Home</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="nav navbar-nav ml-auto">
      <li class="navvar-text mr-2 text-light"><%= current_user_email || "No email found "%></li>
      <li class="nav-item active">
        <form>
          <a class="btn btn-success navbar-btn btn-sm" data-toggle="modal" data-target="#exampleModal" href="#">Ask Questions</a>
        </form>
      </li>
    </ul>
  </div>
</nav>

app/views/home/_new_answer_form.html.erb
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Add New Answer</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= form_for :answer, url: '/answers', html: { class: "form-horizontal" } do %>
          <input type="hidden" name="answer[question_id]" value="<%= @question.id%>">
          <div class="form-group">
            <label for="inputEmail" class="col-sm-2 control-label">Email</label>
            <div class="col-sm-10">
              <input type="email" class="form-control" id="inputEmail1" name="answer[email]" value="<%= current_user_email%>" aria-describedby="emailHelp" placeholder="Enter email" required>
            </div>
          </div>
          <div class="form-group">
            <label for="inputQuestion" class="col-sm-3 control-label">Answer</label>
            <div class="col-sm-10">
              <textarea type="password" class="form-control" id="inputQuestion" name="answer[body]" placeholder="Enter a new answer" required></textarea>
            </div>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            <button type="submit" class="btn btn-primary">Submit</button>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/home/_new_question.html.erb
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">New Question</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= form_for :question, url: '/questions', html: { class: "form-horizontal" } do %>
          <div class="form-group">
            <label for="inputEmail" class="col-sm-2 control-label">Email</label>
            <div class="col-sm-10">
              <input type="email" class="form-control" id="inputEmail1" name="question[email]" value="<%= current_user_email %>" aria-describedby="emailHelp" placeholder="Enter email" required>
            </div>
          </div>
          <div class="form-group">
            <label for="inputQuestion" class="col-sm-3 control-label">Question</label>
            <div class="col-sm-10">
              <textarea type="password" class="form-control" id="inputQuestion" name="question[body]" placeholder="Enter a question" required></textarea>
            </div>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            <button type="submit" class="btn btn-primary">Submit</button>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/home/about.html.erb
<h1>About the application</h1>

app/views/home/index.html.erb
<h1>Welcome to solver!</h1>
<div class="container">
  <div class="media-container">
    <% @questions.each do |question| %>
      <div class="media card flex-row p-2 mb-3" data-target="<%= question_path(question) %>">
        <div class="media-left">
          <img src="http://www.gravatar.com/avatar" class="mr-3" alt="...">
        </div>
        <div class="media-body">
          <h4 class="media-heading">Owner: <%= question.email %></h4>
            <div class="answer-time"><%= time_ago_in_words question.created_at %> ago</div>
            <%= truncate question.body, length: 300 %>
          <div class="view-answer">
            <a href="<%= question_path(question) %>" class="btn btn-success hidden-xs btn-xs">view answers</a>
          </div>
        </div>
      </div>
    <% end %>
  </div>
  <% if @questions.empty?%>
    <div class="aler alert-info">There are no questions right now</div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FirstRails</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.0/css/bootstrap.min.css" integrity="sha384-PDle/QlgIONtM1aqA2Qemk5gPOE7wFq8+Em+G/hmo5Iq0CCmYZLv3fVRDJ4MMwEA" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.0/js/bootstrap.min.js" integrity="sha384-7aThvCh9TypR7fIc2HV4O/nFMVCBwyIUKL8XCtKE+8xgCgl/PQGuFsvShjr74PBp" crossorigin="anonymous"></script>
  </head>

  <body>

    <%= render 'home/navbar' %>  

    <div class="container">
      <%= yield %>

      <%= render 'home/new_question' %>


    </div>
  </body>
</html>

app/views/questions/show.html.erb
<div class="lead card">
  <div class="media p-2">
    <a href="#">
      <img src="http://www.gravatar.com/avatar" class="mr-3" alt="...">
    </a>
    <div class="media-body">
      <h5 class="media-heading"><%= @question.email%></h5>
      <%= @question.body%>
      
      <div class="row mt-5">
        <div class="col-sm-8 col-sm-offset-2 media-container">
          <div>
            <button class="btn btn-success btn-xs mb-3" data-toggle="modal" data-target="#exampleModal">Add new ansers</button>
          </div>
          <%= render 'home/new_answer_form' %>
          <% @answers.map do |answer| %>
          <div class="media card mb-3 p-2 flex-row">
            <div class="media-left">
              <a href="#">
                <img src="http://www.gravatar.com/avatar" class="mr-3" alt="...">
              </a>
            </div>
            <div class="media-body">
              <h5 class="media-heading"><%= answer.email%></h5>
              <div class="answer-time"><%= time_ago_in_words answer.created_at %> ago</div>
              <%= answer.body%>
            </div>
          </div>
          <% end %>
          <% if @answers.empty? %>
            <div class="alert alert-info">There are no answers yet</div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>